schema_version = "1.0.0"

id = "flashy_tools"
version = "0.1.0"
name = "Flashy Tools"
tagline = "Collection of Flash/Animate-like utilities for Blender"
maintainer = "som1sezhi"
# Supported types: "add-on", "theme"
type = "add-on"

# # Optional: link to documentation, support, source files, etc
# website = "https://extensions.blender.org/add-ons/my-example-package/"

# # Optional: tag list defined by Blender and server, see:
# # https://docs.blender.org/manual/en/latest/advanced/extensions/tags.html
# tags = ["Animation", "Sequencer"]

blender_version_min = "5.2.0"
# # Optional: Blender version that the extension does not support, earlier versions are supported.
# # This can be omitted and defined later on the extensions platform if an issue is found.
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/latest/advanced/extensions/licenses.html
license = ["SPDX:GPL-3.0-or-later"]
# # Optional: required by some licenses.
# copyright = [
#   "2002-2024 Developer Name",
#   "1998 Company Name",
# ]

# # Optional: list of supported platforms. If omitted, the extension will be available in all operating systems.
# platforms = ["windows-x64", "macos-arm64", "linux-x64"]
# # Other supported platforms: "windows-arm64", "macos-x64"

dependencies = ['thorvg-python']

# # Optional: bundle 3rd party Python modules.
# # https://docs.blender.org/manual/en/latest/advanced/extensions/python_wheels.html
wheels = [
  "./wheels/thorvg_python-1.1.3-py3-none-macosx_10_9_universal2.whl",
  "./wheels/thorvg_python-1.1.3-py3-none-macosx_10_9_x86_64.whl",
  "./wheels/thorvg_python-1.1.3-py3-none-macosx_11_0_arm64.whl",
  "./wheels/thorvg_python-1.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl",
  "./wheels/thorvg_python-1.1.3-py3-none-win_amd64.whl",
  "./wheels/thorvg_python-1.1.3-py3-none-win_arm64.whl",
  "./wheels/thorvg_python-1.1.3-py3-none-win32.whl",
]

# # Optional: add-ons can list which resources they will require:
# # * files (for access of any filesystem operations)
# # * network (for internet access)
# # * clipboard (to read and/or write the system clipboard)
# # * camera (to capture photos and videos)
# # * microphone (to capture audio)
# #
# # If using network, remember to also check `bpy.app.online_access`
# # https://docs.blender.org/manual/en/latest/advanced/extensions/addons.html#internet-access
# #
# # For each permission it is important to also specify the reason why it is required.
# # Keep this a single short sentence without a period (.) at the end.
# # For longer explanations use the documentation or detail page.
#
[permissions]
files = "Import SVG from disk"
# network = "Need to sync motion-capture data to server"
# clipboard = "Copy and paste bone transforms"

# # Optional: advanced build settings.
# # https://docs.blender.org/manual/en/latest/advanced/command_line/extension_arguments.html#command-line-args-extension-build
[build]
# # These are the default build excluded patterns.
# # You only need to edit them if you want different options.
paths_exclude_pattern = [
  "__pycache__/",
  ".git/",
  ".venv/",
  ".vscode/",
  "build/",
  "dist/",
  "/*.zip",
]
