import bpy
from typing import Literal

# TODO: XZ axis skewing


def compute_shear_transforms_1_node_group() -> bpy.types.NodeTree:
    """Create the Compute Shear Transforms node group.
    Code generated by NodeToPython."""
    compute_shear_transforms_1 = bpy.data.node_groups.new(
        type="GeometryNodeTree", name="Compute Shear Transforms"
    )

    compute_shear_transforms_1.color_tag = "NONE"
    compute_shear_transforms_1.description = ""
    compute_shear_transforms_1.default_group_node_width = 140
    compute_shear_transforms_1.is_modifier = True
    compute_shear_transforms_1.show_modifier_manage_panel = True

    # compute_shear_transforms_1 interface

    # Socket Geometry
    geometry_socket = compute_shear_transforms_1.interface.new_socket(
        name="Geometry", in_out="OUTPUT", socket_type="NodeSocketGeometry"
    )
    geometry_socket.attribute_domain = "POINT"
    geometry_socket.default_input = "VALUE"
    geometry_socket.structure_type = "AUTO"

    # Socket Geometry
    geometry_socket_1 = compute_shear_transforms_1.interface.new_socket(
        name="Geometry", in_out="INPUT", socket_type="NodeSocketGeometry"
    )
    geometry_socket_1.attribute_domain = "POINT"
    geometry_socket_1.default_input = "VALUE"
    geometry_socket_1.structure_type = "AUTO"

    # Socket X Skew
    x_skew_socket = compute_shear_transforms_1.interface.new_socket(
        name="X Skew", in_out="INPUT", socket_type="NodeSocketFloat"
    )
    x_skew_socket.default_value = 0.0
    x_skew_socket.min_value = -3.4028234663852886e38
    x_skew_socket.max_value = 3.4028234663852886e38
    x_skew_socket.subtype = "NONE"
    x_skew_socket.attribute_domain = "POINT"
    x_skew_socket.default_input = "VALUE"
    x_skew_socket.structure_type = "AUTO"

    # Socket Y Skew
    y_skew_socket = compute_shear_transforms_1.interface.new_socket(
        name="Y Skew", in_out="INPUT", socket_type="NodeSocketFloat"
    )
    y_skew_socket.default_value = 0.0
    y_skew_socket.min_value = -3.4028234663852886e38
    y_skew_socket.max_value = 3.4028234663852886e38
    y_skew_socket.subtype = "NONE"
    y_skew_socket.attribute_domain = "POINT"
    y_skew_socket.default_input = "VALUE"
    y_skew_socket.structure_type = "AUTO"

    # Socket Prefix
    prefix_socket = compute_shear_transforms_1.interface.new_socket(
        name="Prefix", in_out="INPUT", socket_type="NodeSocketString"
    )
    prefix_socket.default_value = ""
    prefix_socket.subtype = "NONE"
    prefix_socket.attribute_domain = "POINT"
    prefix_socket.default_input = "VALUE"
    prefix_socket.structure_type = "AUTO"

    # Initialize compute_shear_transforms_1 nodes

    # Node Group Output
    group_output = compute_shear_transforms_1.nodes.new("NodeGroupOutput")
    group_output.name = "Group Output"
    group_output.show_options = True
    group_output.is_active_output = True

    # Node Store Named Attribute
    store_named_attribute = compute_shear_transforms_1.nodes.new(
        "GeometryNodeStoreNamedAttribute"
    )
    store_named_attribute.name = "Store Named Attribute"
    store_named_attribute.show_options = True
    store_named_attribute.data_type = "FLOAT4X4"
    store_named_attribute.domain = "POINT"
    # Selection
    store_named_attribute.inputs[1].default_value = True

    # Node Store Named Attribute.001
    store_named_attribute_001 = compute_shear_transforms_1.nodes.new(
        "GeometryNodeStoreNamedAttribute"
    )
    store_named_attribute_001.name = "Store Named Attribute.001"
    store_named_attribute_001.show_options = True
    store_named_attribute_001.data_type = "FLOAT4X4"
    store_named_attribute_001.domain = "POINT"
    # Selection
    store_named_attribute_001.inputs[1].default_value = True

    # Node Store Named Attribute.002
    store_named_attribute_002 = compute_shear_transforms_1.nodes.new(
        "GeometryNodeStoreNamedAttribute"
    )
    store_named_attribute_002.name = "Store Named Attribute.002"
    store_named_attribute_002.show_options = True
    store_named_attribute_002.data_type = "FLOAT4X4"
    store_named_attribute_002.domain = "POINT"
    # Selection
    store_named_attribute_002.inputs[1].default_value = True

    # Node Combine Transform
    combine_transform = compute_shear_transforms_1.nodes.new(
        "FunctionNodeCombineTransform"
    )
    combine_transform.name = "Combine Transform"
    combine_transform.hide = True
    combine_transform.show_options = True
    # Translation
    combine_transform.inputs[0].default_value = (0.0, 0.0, 0.0)
    # Rotation
    combine_transform.inputs[1].default_value = (0.0, 0.0, 0.0)

    # Node Group Input.003
    group_input_003 = compute_shear_transforms_1.nodes.new("NodeGroupInput")
    group_input_003.name = "Group Input.003"
    group_input_003.show_options = True

    # Node Matrix SVD
    matrix_svd = compute_shear_transforms_1.nodes.new("FunctionNodeMatrixSVD")
    matrix_svd.name = "Matrix SVD"
    matrix_svd.show_options = True

    # Node Combine Matrix
    combine_matrix = compute_shear_transforms_1.nodes.new("FunctionNodeCombineMatrix")
    combine_matrix.name = "Combine Matrix"
    combine_matrix.show_options = True
    combine_matrix.panel_states[0].is_collapsed = False
    combine_matrix.panel_states[1].is_collapsed = False
    combine_matrix.panel_states[2].is_collapsed = True
    combine_matrix.panel_states[3].is_collapsed = True
    # Column 1 Row 1
    combine_matrix.inputs[0].default_value = 1.0
    # Column 1 Row 3
    combine_matrix.inputs[2].default_value = 0.0
    # Column 1 Row 4
    combine_matrix.inputs[3].default_value = 0.0
    # Column 2 Row 2
    combine_matrix.inputs[5].default_value = 1.0
    # Column 2 Row 3
    combine_matrix.inputs[6].default_value = 0.0
    # Column 2 Row 4
    combine_matrix.inputs[7].default_value = 0.0
    # Column 3 Row 1
    combine_matrix.inputs[8].default_value = 0.0
    # Column 3 Row 2
    combine_matrix.inputs[9].default_value = 0.0
    # Column 3 Row 3
    combine_matrix.inputs[10].default_value = 1.0
    # Column 3 Row 4
    combine_matrix.inputs[11].default_value = 0.0
    # Column 4 Row 1
    combine_matrix.inputs[12].default_value = 0.0
    # Column 4 Row 2
    combine_matrix.inputs[13].default_value = 0.0
    # Column 4 Row 3
    combine_matrix.inputs[14].default_value = 0.0
    # Column 4 Row 4
    combine_matrix.inputs[15].default_value = 1.0

    # Node Transpose Matrix
    transpose_matrix = compute_shear_transforms_1.nodes.new(
        "FunctionNodeTransposeMatrix"
    )
    transpose_matrix.name = "Transpose Matrix"
    transpose_matrix.hide = True
    transpose_matrix.show_options = True

    # Node Format String
    format_string = compute_shear_transforms_1.nodes.new("FunctionNodeFormatString")
    format_string.name = "Format String"
    format_string.show_options = True
    format_string.active_index = 0
    format_string.format_items.clear()
    format_string.format_items.new("STRING", "Prefix")
    # Format
    format_string.inputs[0].default_value = "{}_u"

    # Node Reroute
    reroute = compute_shear_transforms_1.nodes.new("NodeReroute")
    reroute.name = "Reroute"
    reroute.show_options = True
    reroute.socket_idname = "NodeSocketString"
    # Node Format String.001
    format_string_001 = compute_shear_transforms_1.nodes.new("FunctionNodeFormatString")
    format_string_001.name = "Format String.001"
    format_string_001.show_options = True
    format_string_001.active_index = 0
    format_string_001.format_items.clear()
    format_string_001.format_items.new("STRING", "Prefix")
    # Format
    format_string_001.inputs[0].default_value = "{}_sigma"

    # Node Format String.002
    format_string_002 = compute_shear_transforms_1.nodes.new("FunctionNodeFormatString")
    format_string_002.name = "Format String.002"
    format_string_002.show_options = True
    format_string_002.active_index = 0
    format_string_002.format_items.clear()
    format_string_002.format_items.new("STRING", "Prefix")
    # Format
    format_string_002.inputs[0].default_value = "{}_v"

    # Set locations
    compute_shear_transforms_1.nodes["Group Output"].location = (
        3993.553955078125,
        -993.3782348632812,
    )
    compute_shear_transforms_1.nodes["Store Named Attribute"].location = (
        3704.425048828125,
        -1150.2181396484375,
    )
    compute_shear_transforms_1.nodes["Store Named Attribute.001"].location = (
        3704.738037109375,
        -762.981689453125,
    )
    compute_shear_transforms_1.nodes["Store Named Attribute.002"].location = (
        3703.203125,
        -954.40625,
    )
    compute_shear_transforms_1.nodes["Combine Transform"].location = (
        3429.5673828125,
        -1049.558837890625,
    )
    compute_shear_transforms_1.nodes["Group Input.003"].location = (
        2686.40283203125,
        -947.7530517578125,
    )
    compute_shear_transforms_1.nodes["Matrix SVD"].location = (
        3212.242431640625,
        -979.9882202148438,
    )
    compute_shear_transforms_1.nodes["Combine Matrix"].location = (
        3034.879150390625,
        -982.527099609375,
    )
    compute_shear_transforms_1.nodes["Transpose Matrix"].location = (
        3426.78759765625,
        -1099.375244140625,
    )
    compute_shear_transforms_1.nodes["Format String"].location = (
        3431.341796875,
        -1278.22021484375,
    )
    compute_shear_transforms_1.nodes["Reroute"].location = (
        2880.125732421875,
        -1335.36083984375,
    )
    compute_shear_transforms_1.nodes["Format String.001"].location = (
        3430.273193359375,
        -1381.892578125,
    )
    compute_shear_transforms_1.nodes["Format String.002"].location = (
        3430.273193359375,
        -1487.7025146484375,
    )

    # Set dimensions
    compute_shear_transforms_1.nodes["Group Output"].width = 140.0
    compute_shear_transforms_1.nodes["Group Output"].height = 100.0

    compute_shear_transforms_1.nodes["Store Named Attribute"].width = 140.0
    compute_shear_transforms_1.nodes["Store Named Attribute"].height = 100.0

    compute_shear_transforms_1.nodes["Store Named Attribute.001"].width = 140.0
    compute_shear_transforms_1.nodes["Store Named Attribute.001"].height = 100.0

    compute_shear_transforms_1.nodes["Store Named Attribute.002"].width = 140.0
    compute_shear_transforms_1.nodes["Store Named Attribute.002"].height = 100.0

    compute_shear_transforms_1.nodes["Combine Transform"].width = 140.0
    compute_shear_transforms_1.nodes["Combine Transform"].height = 100.0

    compute_shear_transforms_1.nodes["Group Input.003"].width = 140.0
    compute_shear_transforms_1.nodes["Group Input.003"].height = 100.0

    compute_shear_transforms_1.nodes["Matrix SVD"].width = 140.0
    compute_shear_transforms_1.nodes["Matrix SVD"].height = 100.0

    compute_shear_transforms_1.nodes["Combine Matrix"].width = 140.0
    compute_shear_transforms_1.nodes["Combine Matrix"].height = 100.0

    compute_shear_transforms_1.nodes["Transpose Matrix"].width = 140.0
    compute_shear_transforms_1.nodes["Transpose Matrix"].height = 100.0

    compute_shear_transforms_1.nodes["Format String"].width = 140.0
    compute_shear_transforms_1.nodes["Format String"].height = 100.0

    compute_shear_transforms_1.nodes["Reroute"].width = 12.5
    compute_shear_transforms_1.nodes["Reroute"].height = 100.0

    compute_shear_transforms_1.nodes["Format String.001"].width = 140.0
    compute_shear_transforms_1.nodes["Format String.001"].height = 100.0

    compute_shear_transforms_1.nodes["Format String.002"].width = 140.0
    compute_shear_transforms_1.nodes["Format String.002"].height = 100.0

    # Initialize compute_shear_transforms_1 links

    # combine_transform.Transform -> store_named_attribute_002.Value
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Combine Transform"].outputs[0],
        compute_shear_transforms_1.nodes["Store Named Attribute.002"].inputs[3],
    )
    # group_input_003.Y Skew -> combine_matrix.Column 1 Row 2
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Group Input.003"].outputs[2],
        compute_shear_transforms_1.nodes["Combine Matrix"].inputs[1],
    )
    # group_input_003.X Skew -> combine_matrix.Column 2 Row 1
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Group Input.003"].outputs[1],
        compute_shear_transforms_1.nodes["Combine Matrix"].inputs[4],
    )
    # combine_matrix.Matrix -> matrix_svd.Matrix
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Combine Matrix"].outputs[0],
        compute_shear_transforms_1.nodes["Matrix SVD"].inputs[0],
    )
    # matrix_svd.V -> transpose_matrix.Matrix
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Matrix SVD"].outputs[2],
        compute_shear_transforms_1.nodes["Transpose Matrix"].inputs[0],
    )
    # matrix_svd.U -> store_named_attribute_001.Value
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Matrix SVD"].outputs[0],
        compute_shear_transforms_1.nodes["Store Named Attribute.001"].inputs[3],
    )
    # transpose_matrix.Matrix -> store_named_attribute.Value
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Transpose Matrix"].outputs[0],
        compute_shear_transforms_1.nodes["Store Named Attribute"].inputs[3],
    )
    # matrix_svd.S -> combine_transform.Scale
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Matrix SVD"].outputs[1],
        compute_shear_transforms_1.nodes["Combine Transform"].inputs[2],
    )
    # group_input_003.Geometry -> store_named_attribute_001.Geometry
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Group Input.003"].outputs[0],
        compute_shear_transforms_1.nodes["Store Named Attribute.001"].inputs[0],
    )
    # store_named_attribute_001.Geometry -> store_named_attribute_002.Geometry
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Store Named Attribute.001"].outputs[0],
        compute_shear_transforms_1.nodes["Store Named Attribute.002"].inputs[0],
    )
    # store_named_attribute_002.Geometry -> store_named_attribute.Geometry
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Store Named Attribute.002"].outputs[0],
        compute_shear_transforms_1.nodes["Store Named Attribute"].inputs[0],
    )
    # store_named_attribute.Geometry -> group_output.Geometry
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Store Named Attribute"].outputs[0],
        compute_shear_transforms_1.nodes["Group Output"].inputs[0],
    )
    # group_input_003.Prefix -> reroute.Input
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Group Input.003"].outputs[3],
        compute_shear_transforms_1.nodes["Reroute"].inputs[0],
    )
    # reroute.Output -> format_string.Prefix
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Reroute"].outputs[0],
        compute_shear_transforms_1.nodes["Format String"].inputs[1],
    )
    # format_string.String -> store_named_attribute_001.Name
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Format String"].outputs[0],
        compute_shear_transforms_1.nodes["Store Named Attribute.001"].inputs[2],
    )
    # reroute.Output -> format_string_001.Prefix
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Reroute"].outputs[0],
        compute_shear_transforms_1.nodes["Format String.001"].inputs[1],
    )
    # reroute.Output -> format_string_002.Prefix
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Reroute"].outputs[0],
        compute_shear_transforms_1.nodes["Format String.002"].inputs[1],
    )
    # format_string_001.String -> store_named_attribute_002.Name
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Format String.001"].outputs[0],
        compute_shear_transforms_1.nodes["Store Named Attribute.002"].inputs[2],
    )
    # format_string_002.String -> store_named_attribute.Name
    compute_shear_transforms_1.links.new(
        compute_shear_transforms_1.nodes["Format String.002"].outputs[0],
        compute_shear_transforms_1.nodes["Store Named Attribute"].inputs[2],
    )

    return compute_shear_transforms_1


def get_single_vertex_mesh_object(sibling: bpy.types.Object) -> bpy.types.Object | None:
    """Get the single-vertex shearcalc object that is a sibling to the given object."""
    if sibling.parent:
        for child in sibling.parent.children:
            if child.name.startswith("_shearcalc") and child.type == "MESH":
                return child
        return None
    else:
        # search for shearcalc obj in same collection as sibling
        # TODO: look for geo nodes modifier matching a wanted prefix
        for collection in sibling.users_collection:
            for obj in collection.objects:
                if (
                    obj.parent is None
                    and obj.name.startswith("_shearcalc")
                    and obj.type == "MESH"
                ):
                    return obj
        return None


def create_single_vertex_mesh_object(sibling: bpy.types.Object) -> bpy.types.Object:
    """Create the single-vertex shearcalc object as a sibling to the given object."""
    # create mesh data with a single vertex, or fetch existing
    mesh = bpy.data.meshes.get("_shearcalc_mesh")
    if mesh is None:
        mesh = bpy.data.meshes.new("_shearcalc_mesh")
        mesh.from_pydata([(0, 0, 0)], [], [])
        mesh.update()

    # create mesh object
    obj = bpy.data.objects.new("_shearcalc", mesh)
    # add shearcalc obj to sibling's collection.
    # an arbitrary collection will be chosen if the sibling is in multiple.
    # all objs belong to at least one collection (i think), so this should
    # always work
    sibling.users_collection[0].objects.link(obj)

    obj.parent = sibling.parent
    obj.hide_viewport = True
    obj.hide_render = True

    return obj


def get_or_create_single_vertex_mesh_object(
    sibling: bpy.types.Object,
) -> bpy.types.Object:
    """Get the single-vertex shearcalc object that is a sibling to the
    given object, or create it if it doens't exist."""
    obj = get_single_vertex_mesh_object(sibling)
    if obj is None:
        obj = create_single_vertex_mesh_object(sibling)
    return obj


def get_shear_transform_node_tree() -> bpy.types.NodeTree:
    node_tree = bpy.data.node_groups.get("Compute Shear Transforms")
    if node_tree is None:
        node_tree = compute_shear_transforms_1_node_group()
    return node_tree


def get_socket_id(node_group: bpy.types.NodeTree, socket_name: str) -> str:
    return node_group.interface.items_tree[socket_name].identifier


PoseBoneOrObject = bpy.types.PoseBone | bpy.types.Object


def has_skew_controls(bone_or_obj: PoseBoneOrObject) -> bool:
    return "Skew" in bone_or_obj.keys()


def add_skew_controls(context: bpy.types.Context, bone_or_obj: PoseBoneOrObject):
    # add or get single-vertex mesh object that is a sibling to armature/object
    if isinstance(bone_or_obj, bpy.types.PoseBone):
        armature_obj = bone_or_obj.id_data
        sibling = armature_obj
    else:
        sibling = bone_or_obj
    shearcalc_obj = get_or_create_single_vertex_mesh_object(sibling)

    # add geometry nodes modifier
    name = bone_or_obj.name
    modifier: bpy.types.NodesModifier = shearcalc_obj.modifiers.new(
        name=f"ComputeShearTransforms_{name}", type="NODES"
    )
    modifier.node_group = get_shear_transform_node_tree()
    # set Prefix of geometry attribute names to bone/object name.
    # edge case: if someone adds skew controls to a bone, renames that bone, and
    # then adds skew controls to a different bone with the first bone's old name,
    # then some naming collision stuff can occur that may be hard to untangle.
    # to avoid this, extract the prefix from the modifier name we're given upon
    # creation, relying on blender's anti-collision renaming to give a unique
    # name for our own purposes
    prefix = modifier.name.split("_", 1)[1]
    prefix_socket_id = get_socket_id(modifier.node_group, "Prefix")
    modifier.properties.inputs[prefix_socket_id]["value"] = prefix
    modifier.node_group.interface_update(context)

    # add custom properties to bone/object
    bone_or_obj["Skew"] = (0.0, 0.0)
    bone_or_obj.property_overridable_library_set('["Skew"]', True)

    # add drivers hooking up custom props to geo nodes inputs
    driver_inputs_outputs = [
        (0, get_socket_id(modifier.node_group, "X Skew")),
        (1, get_socket_id(modifier.node_group, "Y Skew")),
    ]
    for idx, socket_id in driver_inputs_outputs:
        # for some reason we have to add the driver at the object level and
        # write out this full path, or else it says the property is not found
        # or is not animatable
        driver = shearcalc_obj.driver_add(
            f'modifiers["{modifier.name}"].properties.inputs.{socket_id}.value'
        ).driver
        driver.type = "SCRIPTED"
        var = driver.variables.new()
        var.name = "skew"
        var.type = "SINGLE_PROP"
        var.targets[0].id_type = "OBJECT"
        if isinstance(bone_or_obj, bpy.types.PoseBone):
            var.targets[0].id = armature_obj
            var.targets[0].data_path = f'pose.bones["{name}"]["Skew"][{idx}]'
        else:
            var.targets[0].id = bone_or_obj
            var.targets[0].data_path = f'["Skew"][{idx}]'
        driver.expression = var.name

    # add geometry attribute constraints to bone
    for suffix in ("u", "sigma", "v"):
        attr_name = prefix + "_" + suffix
        constraint: bpy.types.GeometryAttributeConstraint = bone_or_obj.constraints.new(
            "GEOMETRY_ATTRIBUTE"
        )
        constraint.name = f"GeometryAttribute_Shear_{attr_name}"
        constraint.target = shearcalc_obj
        constraint.attribute_name = attr_name
        constraint.data_type = "FLOAT4X4"
        constraint.domain = "POINT"
        constraint.sample_index = 0
        constraint.mix_mode = "AFTER_FULL"
        constraint.mix_rot = True
        constraint.mix_scl = True


def check_attribute_usage(shearcalc_obj: bpy.types.Object, prefix: str) -> bool:
    """Return True iff any Geometry Attribute constraints in the project
    have the given target and are using attributes with the given prefix."""

    def _check_constraint(constraint: bpy.types.Constraint):
        return (
            constraint.type == "GEOMETRY_ATTRIBUTE"
            and constraint.name.startswith("GeometryAttribute_Shear_")
            and constraint.target == shearcalc_obj
            and constraint.attribute_name.rsplit("_", 1)[0] == prefix
        )

    for obj in bpy.data.objects:
        if any(map(_check_constraint, obj.constraints)):
            return True
        if obj.pose:
            for pose_bone in obj.pose.bones:
                if any(map(_check_constraint, pose_bone.constraints)):
                    return True
    return False


def remove_skew_controls(
    bone_or_obj: PoseBoneOrObject,
) -> Literal["complete", "partial", "skipped"]:
    # extract info about the geometry nodes modifier (which shearcalc object,
    # which prefix) from the constraints
    shearcalc_obj: bpy.types.Object | None = None
    prefix: str | None = None
    for constraint in bone_or_obj.constraints:
        if (
            constraint.type == "GEOMETRY_ATTRIBUTE"
            and constraint.name.startswith("GeometryAttribute_Shear_")
            and (
                constraint.attribute_name.endswith("_u")
                or constraint.attribute_name.endswith("_sigma")
                or constraint.attribute_name.endswith("_v")
            )
        ):
            prefix = constraint.attribute_name.rsplit("_", 1)[0]
            shearcalc_obj = constraint.target
            break

    # remove custom properties
    deleted_props = False
    if "Skew" in bone_or_obj.keys():
        del bone_or_obj["Skew"]
        deleted_props = True

    # remove geometry attribute constraints
    constraints_to_remove = [
        constraint
        for constraint in bone_or_obj.constraints
        if constraint.type == "GEOMETRY_ATTRIBUTE"
        and constraint.name.startswith("GeometryAttribute_Shear_")
    ]
    for constraint in constraints_to_remove:
        bone_or_obj.constraints.remove(constraint)

    # remove geometry nodes modifier from _shearcalc object
    deleted_modifier = False
    if shearcalc_obj is not None and prefix is not None:
        modifier_name = f"ComputeShearTransforms_{prefix}"
        # only remove the modifier if it exists and no other constraints
        # are using it.
        # e.g. if a bone or object is duplicated, then 2 sets of constraints
        # on 2 different objects now refer to the same modifier's attributes.
        if modifier_name in shearcalc_obj.modifiers and not check_attribute_usage(
            shearcalc_obj, prefix
        ):
            shearcalc_obj.modifiers.remove(shearcalc_obj.modifiers[modifier_name])
            deleted_modifier = True

        # remove shearcalc object if there are no more skew controls
        if len(shearcalc_obj.modifiers) == 0:
            bpy.data.objects.remove(shearcalc_obj, do_unlink=True)

    if deleted_props and len(constraints_to_remove) >= 3 and deleted_modifier:
        return "complete"
    elif deleted_props or len(constraints_to_remove) > 0 or deleted_modifier:
        return "partial"
    else:
        return "skipped"


def get_selection(context: bpy.types.Context):
    if context.mode == "POSE":
        return context.selected_pose_bones
    return context.selected_objects


class FLASHY_OP_add_skew_controls(bpy.types.Operator):
    """Add skew controls to the selected objects or bones."""

    bl_idname = "flashy.add_skew_controls"
    bl_label = "Add Skew Controls"
    bl_options = {"REGISTER", "UNDO"}

    @classmethod
    def poll(cls, context):
        return (
            (context.mode == "POSE" or context.mode == "OBJECT")
            and get_selection(context)  # selection is nonempty
        )

    def execute(self, context):
        add_count = 0
        skip_count = 0
        selection = get_selection(context)
        if selection:
            # add the skew controls
            for bone_or_obj in selection:
                if not has_skew_controls(bone_or_obj):
                    add_skew_controls(context, bone_or_obj)
                    add_count += 1
                else:
                    skip_count += 1

        obj_type = "bone" if context.mode == "POSE" else "object"

        if skip_count == 0:
            message = f"Skew controls added to {add_count} {obj_type}(s)"
        elif add_count == 0:
            message = f"Skew controls already exist on all selected {obj_type}s"
        else:
            message = f"Skew controls added to {add_count} {obj_type}(s) (skipped {skip_count})"
        self.report({"INFO"}, message)

        return {"FINISHED"}


class FLASHY_OP_remove_skew_controls(bpy.types.Operator):
    """Remove skew controls from the selected objects or bones."""

    bl_idname = "flashy.remove_skew_controls"
    bl_label = "Remove Skew Controls"
    bl_options = {"REGISTER", "UNDO"}

    @classmethod
    def poll(cls, context):
        return (
            (context.mode == "POSE" or context.mode == "OBJECT")
            and get_selection(context)  # selection is nonempty
        )

    def execute(self, context):
        counts = {"complete": 0, "partial": 0, "skipped": 0}
        selection = get_selection(context)
        if selection:
            for bone_or_obj in selection:
                result = remove_skew_controls(bone_or_obj)
                counts[result] += 1

        obj_type = "bone" if context.mode == "POSE" else "object"

        if counts["partial"] == 0 and counts["skipped"] == 0:
            message = f"Skew controls removed from {counts['complete']} {obj_type}(s)"
        elif counts["complete"] == 0 and counts["partial"] == 0:
            message = f"No skew controls found on selected {obj_type}s"
        else:
            message = (
                f"Skew controls removed from {counts['complete']} {obj_type}(s) "
                f"({counts['partial']} partially removed, {counts['skipped']} skipped)"
            )
        self.report({"INFO"}, message)

        return {"FINISHED"}


class FLASHY_PT_skew_controls(bpy.types.Panel):
    """Panel for managing skew controls on objects/bones"""

    bl_category = "Flashy"
    bl_label = "Skew Controls"
    bl_idname = "FLASHY_PT_skew_controls"
    bl_space_type = "VIEW_3D"
    bl_region_type = "UI"

    @classmethod
    def poll(cls, context):
        return context.mode == "POSE" or context.mode == "OBJECT"

    def draw(self, context):
        layout = self.layout

        obj_type = "bone" if context.mode == "POSE" else "object"

        if get_selection(context):
            col = layout.column(align=True)
            col.operator(
                "flashy.add_skew_controls", text="Add Skew Controls", icon="ADD"
            )
            col.operator(
                "flashy.remove_skew_controls",
                text="Remove Skew Controls",
                icon="REMOVE",
            )
        else:
            layout.label(text=f"No {obj_type}s selected")


classes = [
    FLASHY_OP_add_skew_controls,
    FLASHY_OP_remove_skew_controls,
    FLASHY_PT_skew_controls,
]


def register():
    for cls in classes:
        bpy.utils.register_class(cls)


def unregister():
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)
